### ISSUE TITLE
Translate the documentation from german into english

### ISSUE THREAD

**Issue by nook24** [it-novum/openITCOCKPIT-documentation#2]
# Hacktoberfest 2021

Celebrate [Hacktoberfest](https://hacktoberfest.digitalocean.com/) by getting involved in the open source community.
We would like to ask you to help us translate the openITCOCKPIT documentation into the **english** language.

*As many as you want* - *as long as you want*

## About the project
openITCOCKPIT is a modern web interface to manage Nagios, Naemon or Prometheus based monitoring environment.

For more information please see the projects home page: https://openitcockpit.io/

## How to contribute

1. Fork this repository
2. Add a comment to this issue, which file you want to translate. (Example: https://github.com/it-novum/openITCOCKPIT-documentation/issues/2#issuecomment-935741141)
3. Clone your forked repository (replace YOUR_ACCOUNT_NAME)
```
git clone https://github.com/YOUR_ACCOUNT_NAME/openITCOCKPIT-documentation.git
cd openITCOCKPIT-documentation/
```
3. Start translating
4. If done, please send a pull request

You can send one pull request per translated file.

## Important notes

To do the translation, **no** special software (like Docker, a programming language or a web server) is required.

We recommend to use a code editor with a spell checker. For most editors are free spell checking plugins available. To name a few:
- [Visual Studio Code](https://code.visualstudio.com/)(free)
- [Notepad++](https://notepad-plus-plus.org/)(free) 
- [Atom](https://atom.io/)(free) 
- [PyCharm Community](https://www.jetbrains.com/pycharm/)(free)

Please do not translate product names or reserved words like:
 - openITCOCKPIT, Statusengine, CakePHP, Gearman, GearmanWorker
 - LDAP, OpenLDAP, PHP, SSO, NRPE, NDO, UUID, ARO, ACO, ACL,
 - Nagios, Naemon, NPCE, NDOUtils
 - Prometheus

### For experts (optional)
If you like to see the end result of your translation, please see the README for instructions on how to run a local copy of the documentation using Docker:
https://github.com/it-novum/openITCOCKPIT-documentation/blob/main/README.md

## Need help or have any question?
 - Please join our community discord server: https://discord.gg/G8KhxKuQ9G

**Comment by nook24** [comment]
I'm going to translate `/de/docs/index.md`

**Comment by PhilippFr** [comment]
going to translate /de/docs/installation.md

**Comment by SvA1** [comment]
I'd like to contribute, I'm going to translate `/de/docs/cheatsheet.md`

**Comment by Aayush2492** [comment]
I'm going to translate `/de/docs/index.md`to english.

**Comment by Aayush2492** [comment]
> I'm would like to translate `/de/docs/index.md`to english.



> I'm would like to translate `/de/docs/index.md`to english.

q

**Comment by mheob** [comment]
I will translate `de/docs/additional/behind-reverse-proxy.md`.
