### ISSUE TITLE
change the navigation bar

### ISSUE THREAD

**Issue by prashantkr006** [it-novum/openITCOCKPIT-documentation#6]
![image](https://user-images.githubusercontent.com/54601213/136201593-8de1d8ed-ca6f-4621-9ba8-c27d4d62648e.png)
this list can be set into navigation bar of the webpage 
and it can look like this
![image](https://user-images.githubusercontent.com/54601213/136201689-eb7d30df-d5dd-41e2-bec2-cbb482eda695.png)
if you like this approach you can assign it to me I will do it. and don't forget to add the Hacktoberfest label into it.

**Comment by nook24** [comment]
Hi @prashantkr006 
Thanks for your idea. We prefer the menu on the left side to avoid any future spacing issues when we get more main bullet points.
